apiVersion: v1
kind: Service
metadata:
  name: "web"
  labels:
    name:  "web"
    major: "<% reactivetrader.web.major %>"
    public: "true"
spec:
  selector:
    name:  "web"
    major: "<% reactivetrader.web.major %>"
  ports:
  - port: 80
    targetPort: 80
    name: "http"
  - port: 8080
    targetPort: 8080
    name: "ws"
  - port: 443
    targetPort: 80
    name: "https"
  - port: 8000
    targetPort: 8080
    name: "wss"
